name: Build and publish to PyPI
on: push
env:
  UV_PYTHON_DOWNLOADS: never
jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Build a binary wheel and a source tarball
      run: |
        uv run --with build python -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v5
      with:
        name: dist
        path: dist
  publish:
    name: Upload release to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/insipid-sphinx-theme
    permissions:
      id-token: write
    steps:
    - name: Get the artifacts
      uses: actions/download-artifact@v5
      with:
        name: dist
        path: dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
